// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image3":
            case "myImage1":return img`
....................
....................
..........ee........
.....eeeeeeeee......
.....eeeeeddee......
....eeddddddee......
....ee11dd11eee.....
.....e1edde1eee.....
......ddddddee......
......99dd99........
..dd9999999999dd....
..dd9999999999dd....
.ddd9999999999ddd...
.ddd9999999999ddd...
..dd9999999999dd....
..ddeeeeeeeeeedd....
....9999999999......
....9999999999......
....dddd..dddd......
....dddd..dddd......
`;
            case "image4":
            case "myImage2":return img`
....................
....................
........ee..........
......eeeeeee.......
......eeeeee........
......eeeeee........
.....eeeed11........
.....eeedd1e........
......eedddd........
........ddd9........
........9dd9........
........9dd9........
........ddd9........
........ddd9........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
            case "image5":
            case "myImage3":return img`
....................
....................
....................
..........ee........
.......eeeeeee......
........eeeeee......
........eeeeeee.....
........11deeee.....
........e1ddee......
........ddddee......
........9ddd........
........9dd9........
........9ddd........
........9ddd........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
            case "image2":
            case "Marinheiro de frente":return img`
.........99...2.....
........9999.2......
.......222222.......
......99999999......
......dddddddd......
.....dddfddfddd.....
......dddddddd......
......ddf22fdd......
.........dd.........
....676a3aaaa252....
....868a3fffa424....
....676f3af3a252....
....868afaf3f424....
....676a3fffa252....
.....d.a3a3aa.d.....
.......a3aa3a.......
........8888........
........8888........
........dddd........
........ffff........
`;
            case "image1":
            case "Marinheiro virado para a direita":return img`
.........99...2.....
........9999.2......
.......222222.......
......999999999.....
.......dddd1e.......
.......dddd11.......
.......dddddd.......
.........dd.........
........2542........
........5245........
........4545........
........2524........
........4522........
........5dd5........
........5dd5........
........2452........
.........88.........
.........88.........
.........dd.........
.........ff.........
`;
            case "image6":
            case "myImage":return img`
....2...99..........
.....2.9999.........
......222222........
.....99999999.......
......e1dddd........
......11dddd........
......dddddd........
....................
....................
........9...........
........9...........
........9..6........
........9..9........
........9..9........
........9..9........
........9999........
.........88.........
.........88.........
.........dd.........
.........ff.........
`;
            case "image8":
            case "myImage6":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. b b b b b b b b b b b b b b . 
. b b b b b b b b b b b b b b . 
. . b b b b b b b b b b b b . . 
. . b b b b b b b b b b b b . . 
. . . b b b b b b b b b b . . . 
. . . b b b b b b b b b b . . . 
. . . . b b b b b b b b . . . . 
. . . . b b b b b b b b . . . . 
. . . . . b b b b b b . . . . . 
. . . . . b b b b b b . . . . . 
. . . . . . b b b b . . . . . . 
. . . . . . b b b b . . . . . . 
. . . . . . . b b . . . . . . . 
`;
            case "image5":
            case "myImage3":return img`
....................
....................
.........ee.........
......eeeeee........
.......eeeeeee......
.......eeeeeee......
........11deeee.....
........e1ddeee.....
........ddddee......
........9dddee......
........9dd9........
........9dd9........
........9ddd........
........9ddd........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
