// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 3 3 3 3 . . . . . . . 
. . . . 3 3 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 . . . . . . 
. . . 3 3 . 3 3 3 3 . . . . . . 
. . . 3 . 3 . 3 3 . 3 . . . . . 
. . . 3 . 3 3 3 3 3 3 3 . . . . 
. . . 3 3 3 3 3 3 . . 3 . . . . 
. . . 3 3 3 . . . . . 3 . . . . 
. . . . 3 3 3 3 3 3 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "myImage0":return img`
.........99...2.....
........9999.2......
.......222222.......
......99999999......
......dddddddd......
.....dddfddfddd.....
......dddddddd......
......ddf22fdd......
.........dd.........
.......a3aaaa252....
.......a3fffa424....
.......f3af3a252....
.......afaf3f424....
.......a3fffa252....
.......a3a3aa.d.....
.......a3aa3a.......
....................
....................
....................
....................
`;
            case "image3":
            case "myImage1":return img`
....................
....................
........ee55........
........e5555.......
.......e55555.......
.......e5eeee.......
.......eeeedd.......
.......eeed11.......
........ddd1e.......
........ddddd.......
........2dd.........
.......2888e........
.......2888e........
.......2888e........
.......2888e........
.......26dd6........
.......26dd6........
.......2266.........
.......2266.........
.......22ff.........
`;
            case "image4":
            case "myImage2":return img`
....................
........55ee........
.......5555e........
.......55555e.......
.......eeee5e.......
.......ddeeee.......
.......11deee.......
.......e1ddd........
.......ddddd........
.........dd.........
........88888.......
........88888.......
........88888.......
........88888.......
........66dd6.......
.........6dd........
.........666........
.........666........
.........666........
.........666........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
