// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 3 3 3 3 . . . . . . . 
. . . . 3 3 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 . . . . . . 
. . . 3 3 . 3 3 3 3 . . . . . . 
. . . 3 . 3 . 3 3 . 3 . . . . . 
. . . 3 . 3 3 3 3 3 3 3 . . . . 
. . . 3 3 3 3 3 3 . . 3 . . . . 
. . . 3 3 3 . . . . . 3 . . . . 
. . . . 3 3 3 3 3 3 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "myImage0":return img`
.........99...2.....
........9999.2......
.......222222.......
......99999999......
......dddddddd......
.....dddfddfddd.....
......dddddddd......
......ddf22fdd......
.........dd.........
.......a3aaaa252....
.......a3fffa424....
.......f3af3a252....
.......afaf3f424....
.......a3fffa252....
.......a3a3aa.d.....
.......a3aa3a.......
....................
....................
....................
....................
`;
            case "image3":
            case "myImage1":return img`
....................
....................
..........ee........
.....eeeeeeeee......
.....eeeeeddee......
....eeddddddee......
....ee11dd11eee.....
.....e1edde1eee.....
......ddddddee......
......99dd99........
..dd9999999999dd....
..dd9999999999dd....
.ddd9999999999ddd...
.ddd9999999999ddd...
..dd9999999999dd....
..ddeeeeeeeeeedd....
....9999999999......
....9999999999......
....dddd..dddd......
....dddd..dddd......
`;
            case "image5":
            case "myImage3":return img`
....................
....................
....................
..........ee........
.......eeeeeee......
........eeeeee......
........eeeeeee.....
........11deeee.....
........e1ddee......
........ddddee......
........9ddd........
........9dd9........
........9ddd........
........9ddd........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
            case "image6":
            case "myImage4":return img`
....................
....................
....................
....................
....................
....................
.......eeee.........
......eeeeee........
........55..........
........55..........
.......eeee.........
......eeeeee........
.....eeeeeeee.......
....eeeeeeeee.......
....eeeeeeeee.......
....eeeeeeeee.......
.....eeeeeee........
......eeeee.........
....................
....................
`;
            case "image7":
            case "myImage5":return img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
bbbbbbbbbbbbbbbbbbbb
.bbbbbbbbbbbbbbbbbb.
..bbbbbbbbbbbbbbbb..
...bbbbbbbbbbbbbb...
....bbbbbbbbbbbb....
.....bbbbbbbbbb.....
......bbbbbbbb......
.......bbbbbb.......
........bbbb........
.........bb.........
`;
            case "image4":
            case "myImage2":return img`
....................
....................
....................
.......eee..........
......eeeeeee.......
......eeeeee........
.....eeeeeee........
.....eeeed11........
......eedd1e........
........dddd........
........ddd9........
........9dd9........
........ddd9........
........ddd9........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
